### PR TITLE
R example -> "shiny". v1beta2 -> v1

### PR DESCRIPTION
**Pull request by mbookman**
Move the "R" example to "shiny".
Update the shiny example to v1 from v1beta2.
Provide more detailed instructions for the shiny example.

### CODE REVIEW

**Comment by deflaux** [comment]
This looks good except can you please add back the R subdirectory with a tiny README.md pointing to the Bioconductor package?

**Comment by mbookman** [comment]
Added a new R/README.md.

**Comment by pgrosu** [comment]
Looks really nice Matt!

Thank you,
~p

**Comment by deflaux** [comment]
LGTM

**Pull request merged**
