### PR TITLE
Fixed instructions in the javascript README

### PR DESCRIPTION
**Pull request by mbookman**
* Client ID type was not specified
* "Authorized redirect URI" --> "Authorized JavaScript origins"

### CODE REVIEW

**Comment by deflaux** [comment]
LGTM

**Comment by pgrosu** [comment]
Hi Matt,

I added both `http://localhost:8000` and `http://127.0.0.1:8000` for **Authorized JavaScript origins** and **Authorized redirect URIs**, and I am still getting the following error when running on Windows - I marked out the personal information:

javascript_client_error

What should I try next?

Thanks,
Paul

**Comment by mbookman** [comment]
Hi Paul - take a look at:

http://stackoverflow.com/questions/36020374/google-permission-denied-to-generate-login-hint-for-target-domain-not-on-localh

In short, you need to use `localhost` rather than `127.0.0.1` in all contexts here.

FWIW, I searched on "permission denied to generate login hint for target domain" to find that - there were a lot of hits, so you are not the only one.

**Comment by pgrosu** [comment]
So I finally got it to work!   So the two key things that made it operational were:

1) I had to create a new `Web Application OAuth client ID` rather use my old one, which provided the `Authorized JavaScript origins` option.

2) In the web browser it was critical to open the web location as `localhost:8000`, as written in the instructions.  I was opening as `127.0.0.1:8000`, which was my fault.

Thanks for the information and weblink,
Paul

**Pull request merged**
